# brew packages
brew "ansible"
brew "ansible-lint"
brew "awscli"
brew "gnupg"
brew "go"
brew "gopls"
brew "python3"
brew "shellcheck"
brew "vim"
brew "ykman"
brew "yubikey-personalization"
# tap brew packages
tap "Yleisradio/terraforms"
brew "chtf"
tap "golangci/tap"
brew "golangci-lint"
# casks
cask "bitwarden"
cask "iterm2"
cask "tunnelblick"
# tap casks
tap "homebrew/cask-drivers"
