---
- name: ~/bin in path
  lineinfile:
    path: ~/.bash_profile
    regexp: "export PATH="
    line: "export PATH=$HOME/bin:$PATH"
    owner: "{{ username }}"
    mode: 0644
- name: shell completion
  lineinfile:
    path: ~/.bash_profile
    regexp: "bash_completion.sh"
    line: "[[ -r '/usr/local/etc/profile.d/bash_completion.sh' ]] && . '/usr/local/etc/profile.d/bash_completion.sh'"
    create: yes
    insertafter: "export PATH="
    owner: "{{ username }}"
    mode: 0644
