---
- name: "ruby {{ ruby_version }}"
  command:
    cmd: "ruby-install {{ ruby_version }}"
    creates: "~/.rubies/ruby-{{ ruby_version }}"

- name: "bundler gem"
  command:
    cmd: "~/.rubies/ruby-{{ ruby_version }}/bin/gem install bundler"
    creates: "~/.gem/ruby/{{ ruby_version }}/gems/bundler-*"
