---
- name: ~/bin exists
  file:
    name: ~/bin
    state: directory
    mode: 0755
    owner: jylitalo

- name: ~/bin in path
  lineinfile:
    path: ~/.zshrc
    regexp: "export PATH="
    line: "export PATH=$HOME/bin:$PATH"
    owner: jylitalo
    mode: 0644

- name: chtf and chruby in ~/.zshrc
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    marker: "# {mark} chtf & chruby ANSIBLE MANAGED BLOCK"
    create: yes
    mode: 0644
    block: |
      source /usr/local/opt/chruby/share/chruby/chruby.sh
      source /usr/local/opt/chruby/share/chruby/auto.sh
      chruby {{ ruby_version }}
      source /usr/local/opt/chtf/share/chtf/chtf.sh
      chtf 0.15.4

- name: shell prompt in ~/.zshrc
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    marker: "# {mark} prompt ANSIBLE MANAGED BLOCK"
    create: yes
    mode: 0644
    block: |
      setopt prompt_subst
      autoload -Uz vcs_info
      zstyle ':vcs_info:*' actionformats '%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
      zstyle ':vcs_info:*' formats '%F{5}[%F{2}%b%F{5}]%f '
      zstyle ':vcs_info:*' enable git
      vcs_info_wrapper() {
        vcs_info
        if [ -n "$vcs_info_msg_0_" ]; then
          echo "%{$fg[grey]%}${vcs_info_msg_0_}%{$reset_color%}$del"
        fi
      }
      RPROMPT=$'$(vcs_info_wrapper)'
      PROMPT="[%m:%~]%# "
