---
- name: setup dotfiles under user's HOME
  hosts: localhost
  vars:
    username: jylitalo
  tasks:
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/gpg.yml
    - include_tasks: tasks/terraform.yml
    - include_tasks: tasks/vim.yml
    - include_tasks: tasks/vscode.yml
    - include_tasks: tasks/zsh.yml
