---
- name: setup dotfiles under user's HOME
  hosts: localhost
  vars:
    ruby_version: 3.0.1
  tasks:
    - include: tasks/ruby.yml
    - include: tasks/vim.yml
    - include: tasks/vscode.yml
    - include: tasks/zsh.yml
